on:
  workflow_call:
    inputs:
      extension-name:
        required: true
        type: string
        description: The name of the extension to test
      mw-branch:
        required: true
        type: string
        description: The branch of MediaWiki to clone
      mw-git-origin:
        default: 'wikimedia/mediawiki'
        required: false
        type: string
        description: The GitHub repository which should be used to clone MediaWiki
      php-version:
        required: true
        type: string
        description: The PHP version to install
      php-extensions:
        default: ''
        required: false
        type: string
        description: The PHP extensions (separated by commas) to install
      phpunit:
        default: true
        required: false
        type: boolean
        description: Whether to run PHPUnit
      parser-tests:
        required: false
        type: string
        description: Path to the directory containing parser tests to run
      phan:
        default: true
        required: false
        type: boolean
        description: Whether to run phan
      experimental:
        default: false
        required: false
        type: boolean
        description: Whether to continue if an error occurs during the CI run

jobs:
  phan:
    if: inputs.phan
    name: "Phan: MW ${{ inputs.mw-branch }}, PHP ${{ inputs.php-version }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.experimental }}
    steps:
      - uses: $/actions/install-mw
        with:
          mw-branch: ${{ inputs.mw-branch }}
          mw-git-origin: ${{ inputs.mw-git-origin }}
          extension-name: ${{ inputs.extension-name }}
          php-version: ${{ inputs.php-version }}
          php-extensions: ${{ inputs.php-extensions }}
          extension-composer-install: true
          setup-db: false

      - name: Run phan
        run: composer run phan
        working-directory: mediawiki/extensions/${{ inputs.extension-name }}

  tests:
    if: inputs.phpunit || inputs.parser-tests
    name: "Tests: MW ${{ inputs.mw-branch }}, PHP ${{ inputs.php-version }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.experimental }}
    steps:
      - uses: $/actions/install-mw
        with:
          mw-branch: ${{ inputs.mw-branch }}
          mw-git-origin: ${{ inputs.mw-git-origin }}
          extension-name: ${{ inputs.extension-name }}
          php-version: ${{ inputs.php-version }}
          php-extensions: ${{ inputs.php-extensions }}
          extension-composer-install: false
          setup-db: true

      - name: Run PHPUnit
        if: inputs.phpunit
        run: composer run phpunit extensions/${{ inputs.extension-name }}/tests
        working-directory: mediawiki
      
      - name: Run parser tests
        if: inputs.parser-tests
        run: php tests/parser/parserTests.php --dir=${{ inputs.parser-tests }}
        working-directory: mediawiki
